/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package processamentodigitalimagem;

//import com.sun.istack.internal.logging.Logger;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author dn34083
 */
public class Tela extends javax.swing.JFrame {
    
    
    private Imagem imagemObj = new Imagem();
  // private JLabel lblImagem = new JLabel();
     private BufferedImage imagemOriginal;
     private BufferedImage imagemAlterada; 

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     private void carregaImagemOriginal() {
           atualizaDadosImagem();
    }
     
     private void atualizaDadosImagem() {
        
     }
     
     private void carregaImagem(File arquivo) throws IOException {
        this.imagemOriginal = ImageIO.read(arquivo);
       // this.painelImagemOriginal.setImagem(imagemOriginal);
        carregaImagemOriginal();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jpanel0 = new javax.swing.JPanel();
        txtMedia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMediana = new javax.swing.JTextField();
        btCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtModa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVarianciaa = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btExercicio = new javax.swing.JButton();
        cboxExercicio = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTransladarX = new javax.swing.JTextField();
        txtTransladarY = new javax.swing.JTextField();
        btTransladar = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cboxDirecao = new javax.swing.JComboBox();
        btEspelhar = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cboxRotacao = new javax.swing.JComboBox();
        btRotacao = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sliderZoom = new javax.swing.JSlider();
        btZoom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblImagem = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblImagembkp = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bAbrirImagem = new javax.swing.JMenuItem();
        btSalvar = new javax.swing.JMenuItem();
        btEdit = new javax.swing.JMenu();
        btHistograma = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btReset = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btBrilhoMais = new javax.swing.JMenuItem();
        btBrilhoMenos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        btContrasteMais = new javax.swing.JMenuItem();
        btContrasteMenos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btCinza = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btRuidos = new javax.swing.JMenuItem();
        btBordas = new javax.swing.JMenuItem();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jpanel0.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Media:");

        jLabel2.setText("Mediana:");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        jLabel3.setText("Moda:");

        jLabel4.setText("Variância:");

        javax.swing.GroupLayout jpanel0Layout = new javax.swing.GroupLayout(jpanel0);
        jpanel0.setLayout(jpanel0Layout);
        jpanel0Layout.setHorizontalGroup(
            jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel0Layout.createSequentialGroup()
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel0Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMediana, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(txtModa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVarianciaa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpanel0Layout.setVerticalGroup(
            jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMedia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMediana)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtModa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtVarianciaa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Exercício A,B,C,D e E :");

        btExercicio.setText("Executar");
        btExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExercicioActionPerformed(evt);
            }
        });

        cboxExercicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E" }));
        cboxExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxExercicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btExercicio, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxExercicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(45, 45, 45)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxExercicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btExercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(107, 104));

        jLabel7.setText("Transladar Imagem");

        jLabel8.setText("Transladar em x:");

        jLabel9.setText("Transladar em y:");

        txtTransladarX.setText(" ");

        btTransladar.setText("Executar");
        btTransladar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransladarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTransladarY)
                            .addComponent(txtTransladarX))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btTransladar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTransladarX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTransladarY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btTransladar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Espelhar:");

        cboxDirecao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Horizontal", "Vertical" }));

        btEspelhar.setText("Executar");
        btEspelhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEspelharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btEspelhar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(cboxDirecao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxDirecao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btEspelhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setText("Rotacao");

        cboxRotacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "90°", "180°" }));

        btRotacao.setText("Executar");
        btRotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRotacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btRotacao, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(cboxRotacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxRotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRotacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setText("Zoom:");

        sliderZoom.setMajorTickSpacing(1);
        sliderZoom.setMaximum(4);
        sliderZoom.setMinimum(-4);
        sliderZoom.setPaintLabels(true);
        sliderZoom.setToolTipText("");
        sliderZoom.setValue(0);
        sliderZoom.setValueIsAdjusting(true);
        sliderZoom.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                sliderZoomAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                sliderZoomAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btZoom.setText("Aplicar");
        btZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btZoom)
                .addGap(60, 60, 60))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btZoom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagem.setAutoscrolls(true);
        lblImagem.setOpaque(true);
        jScrollPane1.setViewportView(lblImagem);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblImagembkp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagembkp.setOpaque(true);
        jScrollPane2.setViewportView(lblImagembkp);

        jMenu1.setText("Arquivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        bAbrirImagem.setText("Abrir Imagem");
        bAbrirImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirImagemActionPerformed(evt);
            }
        });
        jMenu1.add(bAbrirImagem);

        btSalvar.setText("Salvar alterações");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(btSalvar);

        jMenuBar1.add(jMenu1);

        btEdit.setText("Editar");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        jMenuBar1.add(btEdit);

        btHistograma.setText("Funções");

        jMenuItem1.setText("Gerar Histograma");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        btHistograma.add(jMenuItem1);

        btReset.setText("Restaurar Matriz");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        btHistograma.add(btReset);

        jMenu4.setText("Brilho");

        btBrilhoMais.setText("Brilho +");
        btBrilhoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrilhoMaisActionPerformed(evt);
            }
        });
        jMenu4.add(btBrilhoMais);

        btBrilhoMenos.setText("Brilho -");
        btBrilhoMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBrilhoMenosActionPerformed(evt);
            }
        });
        jMenu4.add(btBrilhoMenos);

        btHistograma.add(jMenu4);

        jMenu5.setText("Contraste");

        btContrasteMais.setText("Contraste +");
        btContrasteMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContrasteMaisActionPerformed(evt);
            }
        });
        jMenu5.add(btContrasteMais);

        btContrasteMenos.setText("Contraste -");
        btContrasteMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContrasteMenosActionPerformed(evt);
            }
        });
        jMenu5.add(btContrasteMenos);

        btHistograma.add(jMenu5);

        jMenuBar1.add(btHistograma);

        jMenu2.setText("Tonalidades de Cinza");

        btCinza.setText("Tonalidade Cinza -1");
        btCinza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCinzaActionPerformed(evt);
            }
        });
        jMenu2.add(btCinza);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Filtros");

        btRuidos.setText("Extração de Ruídos");
        btRuidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRuidosActionPerformed(evt);
            }
        });
        jMenu3.add(btRuidos);

        btBordas.setText("Detecção de Bordas");
        jMenu3.add(btBordas);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanel0, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAbrirImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirImagemActionPerformed
        // TODO add your handling code here:
                 try {
            BufferedImage img = this.imagemObj.find_imagem();
            
            if(img != null){

                this.showImageoriginal(img);
            }
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
   //}                                      

    }//GEN-LAST:event_bAbrirImagemActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEditActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.imagemObj.gera_histograma();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        // TODO add your handling code here:
        txtMediana.setText(this.imagemObj.getMediana());
        txtMedia.setText(this.imagemObj.getMedia());
        txtModa.setText(this.imagemObj.getModa());
        txtVarianciaa.setText(this.imagemObj.getVariancia());
    }//GEN-LAST:event_btCalcularActionPerformed

    private void btExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExercicioActionPerformed
        // TODO add your handling code here:
        String teste = cboxExercicio.getSelectedItem().toString();
        //System.out.println(teste);
        BufferedImage imgNova = this.imagemObj.getImagemExercicio(teste);
        this.showImage(imgNova);
    }//GEN-LAST:event_btExercicioActionPerformed

    private void cboxExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxExercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxExercicioActionPerformed

    private void btTransladarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransladarActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(txtTransladarX.getText().trim());
        int y = Integer.parseInt(txtTransladarY.getText().trim());

        if((x >= 0) && (y >= 0)){

            Integer matriz[][][] = this.imagemObj.getMatrizTranslacao(x,y); 
            this.showImage(this.imagemObj.createImagemByMatriz(matriz));
        }else{
            JOptionPane.showInputDialog(this, "Informe valores válidos (x > 0 e y > 0)");
        }
    }//GEN-LAST:event_btTransladarActionPerformed

    private void btEspelharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEspelharActionPerformed
        // TODO add your handling code here:
        
        Integer matriz[][][] = this.imagemObj.getMatrizEspelhamento(cboxDirecao.getSelectedIndex());
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));    
        
    }//GEN-LAST:event_btEspelharActionPerformed

    private void btRotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRotacaoActionPerformed
        // TODO add your handling code here:
        int graus = 0;
        if (cboxRotacao.getSelectedIndex() == 0){
            graus = 90;
        }else {
            graus =180;
        }
        Integer matriz[][][] = this.imagemObj.getMatrizRotacao(graus);
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));
    }//GEN-LAST:event_btRotacaoActionPerformed

    private void sliderZoomAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sliderZoomAncestorMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sliderZoomAncestorMoved

    private void sliderZoomAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_sliderZoomAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_sliderZoomAncestorAdded

    private void btZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZoomActionPerformed
        // TODO add your handling code here:
        double zoom = 0;
        double aux = sliderZoom.getValue();
        double altura;
        double largura;
        switch ((int)aux){
            case 1:
                zoom =1.1;
               
            break;
            case 2:
                zoom =1.2;
            break;  
            case -1:
                zoom =0.9;
            break;
            case -2:
                zoom =0.8;
            break;
            case 0:
                zoom =1;
            break;    
            case 3:
                zoom = 1.3;
                break;
            case -3:
                zoom = 0.7;
                break;
            case 4:
                zoom =1.4;
            break;
            case -4:
                zoom =0.6;
            break; 
        }
        Integer matriz[][][] = this.imagemObj.getZoom(zoom);
        
      //  System.out.println("Valor de Zoom " + aux );
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));
        
    }//GEN-LAST:event_btZoomActionPerformed

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        // TODO add your handling code here:
        Integer matriz[][][] = this.imagemObj.resetMatriz();
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));
        
    }//GEN-LAST:event_btResetActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        Integer matriz[][][] = this.imagemObj.getSalvar();
        this.showImageoriginal(this.imagemObj.createImagemByMatriz(matriz));
       
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCinzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCinzaActionPerformed
        // TODO add your handling code here:
        Integer matriz[][][] = this.imagemObj.getMatrizCinza();
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));
    }//GEN-LAST:event_btCinzaActionPerformed

    private void btRuidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRuidosActionPerformed
        // TODO add your handling code here:
        Integer matriz[][][] = this.imagemObj.getExtracaoRuidos();
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));
        
    }//GEN-LAST:event_btRuidosActionPerformed

    private void btBrilhoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrilhoMaisActionPerformed
        int brilho = 50;
        Integer matriz[][][] = this.imagemObj.getBrilho(brilho);
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));
    }//GEN-LAST:event_btBrilhoMaisActionPerformed

    private void btBrilhoMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBrilhoMenosActionPerformed
        int brilho = -2;
        Integer matriz[][][] = this.imagemObj.getBrilho(brilho);
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));
    }//GEN-LAST:event_btBrilhoMenosActionPerformed

    private void btContrasteMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContrasteMaisActionPerformed
        int contraste = 2;
        Integer matriz[][][] = this.imagemObj.getContraste(contraste);
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));
    }//GEN-LAST:event_btContrasteMaisActionPerformed

    private void btContrasteMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContrasteMenosActionPerformed
        int contraste = -50;
        Integer matriz[][][] = this.imagemObj.getContraste(contraste);
        this.showImage(this.imagemObj.createImagemByMatriz(matriz));
    }//GEN-LAST:event_btContrasteMenosActionPerformed

    public static File getApplicationImagesPath(){
       File folder = new File("./imagens/");
       return folder;
     }
    private void showImage(BufferedImage img){
        ImageIcon icon = new ImageIcon(img);
        //lblImagem.setSize(img.getWidth(), img.getHeight());
            
        lblImagem.setIcon(icon);
       
    }private void showImageoriginal(BufferedImage img){
        ImageIcon icon = new ImageIcon(img);
        //lblImagembkp.setSize(img.getWidth(), img.getHeight());
        lblImagembkp.setIcon(icon);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bAbrirImagem;
    private javax.swing.JMenuItem btBordas;
    private javax.swing.JMenuItem btBrilhoMais;
    private javax.swing.JMenuItem btBrilhoMenos;
    private javax.swing.JButton btCalcular;
    private javax.swing.JMenuItem btCinza;
    private javax.swing.JMenuItem btContrasteMais;
    private javax.swing.JMenuItem btContrasteMenos;
    private javax.swing.JMenu btEdit;
    private javax.swing.JToggleButton btEspelhar;
    private javax.swing.JButton btExercicio;
    private javax.swing.JMenu btHistograma;
    private javax.swing.JMenuItem btReset;
    private javax.swing.JToggleButton btRotacao;
    private javax.swing.JMenuItem btRuidos;
    private javax.swing.JMenuItem btSalvar;
    private javax.swing.JToggleButton btTransladar;
    private javax.swing.JButton btZoom;
    private javax.swing.JComboBox cboxDirecao;
    private javax.swing.JComboBox cboxExercicio;
    private javax.swing.JComboBox cboxRotacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanel0;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblImagembkp;
    private static javax.swing.JSlider sliderZoom;
    private javax.swing.JTextField txtMedia;
    private javax.swing.JTextField txtMediana;
    private javax.swing.JTextField txtModa;
    private javax.swing.JTextField txtTransladarX;
    private javax.swing.JTextField txtTransladarY;
    private javax.swing.JTextField txtVarianciaa;
    // End of variables declaration//GEN-END:variables
}
